package ibcompsci.urdenwaz.shouldidodge.ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.Rectangle;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextField;

import ibcompsci.urdenwaz.shouldidodge.engine.ApiClient;
import ibcompsci.urdenwaz.shouldidodge.objects.FontGenerator;
import ibcompsci.urdenwaz.shouldidodge.objects.InteractivePanel;
import ibcompsci.urdenwaz.shouldidodge.objects.Toolbar;

public class MainUI extends JFrame {
	
	private ApiClient client;

    private JButton dodgeButton;
    private JLabel appNameLabel;
    private JPanel mainUIPanel;
    private JSplitPane topSplitPane;
    private JLabel topLabel;
    private JTextField topSummonerField;
    private JSplitPane topChampPane;
    private JLabel topChampLabel;
    private JTextField topChampField;
    private JSplitPane jungSplitPane;
    private JLabel jungLabel;
    private JTextField jungSummonerField;
    private JSplitPane jungleChampPane;
    private JLabel jungChampLabel;
    private JTextField jungChampField;
    private JSplitPane midPane;
    private JTextField midSummonerField;
    private JSplitPane midChampPane;
    private JTextField midChampField;
    private JSplitPane botPane;
    private JLabel midLabel;
    private JLabel midChampLabel;
    private JLabel botLabel;
    private JTextField botSummonerField;
    private JSplitPane botChampPane;
    private JLabel botChampLabel;
    private JTextField botChampField;
    private JSplitPane supPane;
    private JSplitPane supChampPane;
    private JLabel supLabel;
    private JLabel supChampLabel;
    private JTextField supSummonerField;
    private JTextField supChampField;

    // Width should be AT LEAST 400. Recommended 500-750.
    private final int SCREEN_WIDTH = 500;
    private final int SCREEN_HEIGHT = 750;
    
    private Rectangle[] mainFields;
    private JPanel[] mainPanels;
    
    private int mouseX;
    private int mouseY;
    
    public MainUI(String name, ApiClient client) {
        super(name);
        this.client = client;
        init();
    }
    
    public void init() {
//    	setUndecorated(true);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(new Rectangle(100, 100, SCREEN_WIDTH, SCREEN_HEIGHT));
		setUndecorated(true);
		
		setBackground(new java.awt.Color(255, 255, 255, 255));
		
		mainUIPanel = new JPanel();
		
		setContentPane(mainUIPanel);
		mainUIPanel.setLayout(null);
		mainUIPanel.setBackground(Color.WHITE);
		mainUIPanel.setBorder(new javax.swing.border.LineBorder(Color.BLACK));
		
		/// dimensions for title, player, and button fields indexed at 0,1,2 respectively.
		mainFields = getMainFields();
		mainPanels = getMainPanels();
		
		
		mainPanels[0].addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mousePressed(java.awt.event.MouseEvent evt) {
				framePress(evt);
			}
		});
		mainPanels[0].addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			@Override
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				frameDrag(evt);
			}
		});
		
		
		
    }
    
    private Rectangle[] getMainFields() {
    	int tbHeight = 20; // toolbar height
    	return new Rectangle[] {
    			new Rectangle(0, 0, SCREEN_WIDTH, tbHeight),
    			new Rectangle(0, tbHeight, SCREEN_WIDTH, (SCREEN_HEIGHT-tbHeight)*1/10+1), // graphics start from top left.
    			new Rectangle(0, SCREEN_HEIGHT*1/10+tbHeight, SCREEN_WIDTH, (SCREEN_HEIGHT-tbHeight)*9/10+1)
    		};
    }
    
    private JPanel[] getMainPanels() {
    	JPanel[] ret = new JPanel[mainFields.length];
    	
    	JPanel r;
    	
    	// toolbar panel
    	r = new Toolbar(this);
    	r.setBackground(Color.BLACK);
    	
    	ret[0] = r;
    	
    	// title panel
    	
    	r = new JPanel();
    	r.setOpaque(true);
    	r.setBorder(new javax.swing.border.LineBorder(Color.BLACK));
    	
    	JLabel testLabel = new JLabel("ShouldIDodge.GG");
		testLabel.setFont(FontGenerator.$$$getFont$$$("Comic Sans MS", -1, 48, testLabel.getFont()));
		r.add(testLabel);
		
    	ret[1] = r;
    	
    	// Interactive panel
    	
    	InteractivePanel ip = new InteractivePanel(client);
    	ret[2] = ip;
    	
    	// standardized formatting of panels
		for (int i = 0; i < mainFields.length; i++) {
			ret[i].setBounds(mainFields[i]);
			ret[i].setBorder(new javax.swing.border.LineBorder(Color.BLACK));
			ret[i].setOpaque(true);
			mainUIPanel.add(ret[i]);
		}
		
		return ret;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
//        $$$setupUI$$$();
    }
    
    public void frameDrag(java.awt.event.MouseEvent evt) {
    	int x = evt.getXOnScreen();
    	int y = evt.getYOnScreen();
    	
    	this.setLocation(x - mouseX, y - mouseY);
    }
    
    public void framePress(java.awt.event.MouseEvent evt) {
    	mouseX = evt.getX();
    	mouseY = evt.getY();
    }
   
    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainUIPanel;
    }

}
